# Set prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse

# Vi mode
set -g mode-keys vi
set -g escape-time 0

# tmux sensible
set -g aggressive-resize on
set -g base-index 1
set -g focus-events
set -g display-time 4000
set -g history-limit 50000
set -g status-interval 5
set -g status-keys emacs
bind C-p previous-window
bind C-n next-window

# Undercurl support
# set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Vim key mappings for selection and copy
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Vim-like windows splits in the CWD! :)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Search window in current session
bind C-w display-popup -E "\
    tmux list-windows -F '#{window_index} #{window_name}' \
    | sed '/^$/d' \
    | fzf --reverse --header 'Jump to window' \
    | cut -d ' ' -f 1 \
    | xargs tmux select-window -t"

# Search session
bind C-s display-popup -E "\
    tmux list-sessions -F '#{?session_attached,,#{session_name}}' \
    | sed '/^$/d' \
    | fzf --reverse --header 'Jump to session' \
    | xargs tmux switch-client -t"

# lazygit popup
bind C-g display-popup \
    -d "#{pane_current_path}" \
    -w 80% \
    -h 80% \
    -E "lazygit"

# jjui popup
bind C-j display-popup \
    -d "#{pane_current_path}" \
    -w 80% \
    -h 80% \
    -E "jjui"

#### Design ####
# panes
set -g pane-border-style 'fg=#333333'
set -g pane-active-border-style 'fg=green'

# statusbar
set -g status-position top
set -g status-justify left
set -g status-style 'fg=terminal bg=terminal'

set -g status-left ' #S '
set -g status-left-style 'fg=terminal bg=#333333'
set -g status-left-length 16

set -g status-right "#{=51:pane_title} #[bg=#333333] %H:%M | %m/%d/%y "
set -g status-right-length 70

set -g window-status-separator ''
set -g window-status-current-style 'fg=black bg=green'
set -g window-status-current-format ' #I #W #F '

set -g window-status-style 'fg=green bg=terminal'
set -g window-status-format ' #I #W #F '
