# Undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Vim key mappings for selection and copy
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Vim-like windows splits in the CWD! :)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Search window in current session
bind C-w display-popup -E "\
    tmux list-windows -F '#{window_index} #{window_name}' |\
    sed '/^$/d' |\
    fzf --reverse --header 'Jump to window' |\
    cut -d ' ' -f 1 |\
    xargs tmux select-window -t"

# Search session
bind C-s display-popup -E "\
    tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
    sed '/^$/d' |\
    fzf --reverse --header 'Jump to session' |\
    xargs tmux switch-client -t"

bind C-g display-popup \
    -d "#{pane_current_path}" \
    -w 80% \
    -h 80% \
    -E "lazygit"

#### Design ####
# copy mode
# setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=#333333'
set -g pane-active-border-style 'fg=green'

# statusbar
set -g status-position top
set -g status-justify left
set -g status-style 'fg=terminal bg=terminal'

set -g status-left ' #S '
set -g status-left-style 'fg=terminal bg=#333333'
set -g status-left-length 16
#
# set -g status-right "#[align=absolute-centre][#{=50:pane_title}]#[align=right bg=#333333] %H:%M | %m/%d/%y "
set -g status-right "#{=51:pane_title} #[bg=#333333] %H:%M | %m/%d/%y "
set -g status-right-length 70
# set -g status-right-style 'fg=terminal bg=#333333'

set -g window-status-separator ''
set -g window-status-current-style 'fg=black bg=green'
set -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=green bg=terminal'
setw -g window-status-format ' #I #W #F '

# setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
# set -g message-style 'fg=yellow bg=red bold'
