# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-471aa0bc-4925-41f6-a9fd-41a3dfdece83";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-471aa0bc-4925-41f6-a9fd-41a3dfdece83".device = "/dev/disk/by-uuid/471aa0bc-4925-41f6-a9fd-41a3dfdece83";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/45CC-F4F6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d03e09d2-e7ca-4e30-a097-4a24a37b7858"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
